### ISSUE TITLE
风哥，工具用不了了，啥时候更新呀

### ISSUE THREAD

**Issue by sunkeepero** [tangxiaofeng7/Fofa-collect#2]

**Comment by tangxiaofeng7** [comment]
ip转换的功能，因为站长之家的变化导致不能用，fofa高级会员的key因为滥用已经被封了，换成自己的key就行

**Comment by sunkeepero** [comment]
哦，好的，谢谢！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "wyzxxz-紫霞仙子大佬"<notifications@github.com&gt;; 
发送时间: 2020年10月28日(星期三) 下午2:31
收件人: "tangxiaofeng7/Fofa-collect"<Fofa-collect@noreply.github.com&gt;; 
抄送: "安暖相伴"<984084954@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [tangxiaofeng7/Fofa-collect] 风哥，工具用不了了，啥时候更新呀 (#2)





 
ip转换的功能，因为站长之家的变化导致不能用，fofa高级会员的key因为滥用已经被封了，换成自己的key就行
