### ISSUE TITLE
取值函数String.valueOf(client.getData(q, i)).trim()重复

### ISSUE THREAD

**Issue by Tomassky** [tangxiaofeng7/Fofa-collect#9]
大佬您好，在源码中，master/src/main/java/com/suyu/controller路径下的FofaController.java第74行，出现了两次请求取值，导致返回的数据出问题a = String.valueOf(client.getData(String.valueOf(client.getData(q, i)))).trim();，求大佬验证一下是否有问题

**Comment by tangxiaofeng7** [comment]
V3.2已修复
